changelog:
  categories:
    - title: "Features"
      labels:
        - "feat"
        - "feature"
    - title: "Fixes"
      labels:
        - "fix"
        - "bug"
    - title: "Docs"
      labels:
        - "docs"
    - title: "Maintenance"
      labels:
        - "chore"
        - "refactor"
        - "test"
  exclude:
    labels:
      - "skip-changelog"
